<?php
                        if(isset($_GET['search'])){
                            $search=$_GET['search'];
                        }
                        $page=1;
                        if(isset($_GET['page'])){
                            $page=$_GET['page'];
                        }
                        $all_page=ceil($all_product/4);
                        $skip_page=4*($page-1);
